# Generated by Django 6.0 on 2026-01-16 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('reference', models.CharField(max_length=100, verbose_name='reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='status')),
                ('paystack_response', models.JSONField(blank=True, null=True, verbose_name='paystack response')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('webhook_event_id', models.CharField(blank=True, help_text='Paystack event ID for idempotency', max_length=100, null=True, unique=True, verbose_name='webhook event id')),
                ('verified_via_webhook', models.BooleanField(default=False, help_text='True if payment status was updated via webhook', verbose_name='verified via webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
