# Generated by Django 6.0 on 2026-01-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseenrollment'),
        ('users', '0004_alter_profile_date_of_birth_parent_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-user__date_joined'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship_to_student',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories student is interested in', related_name='students', to='courses.category'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Primary parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.parent'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='users_stude_student_908f14_idx'),
        ),
    ]
