# Generated by Django 6.0 on 2026-01-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursebookmark'),
        ('users', '0005_alter_student_options_parent_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['linking_code'], name='users_stude_linking_b1bd3b_idx'),
        ),
    ]
