# Generated by Django 6.0 on 2025-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_created_by_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='cover image url'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_video',
            field=models.URLField(blank=True, verbose_name='cover video url'),
        ),
    ]
