# Generated by Django 6.0 on 2025-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_cover_image_alter_course_cover_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_video',
            field=models.URLField(blank=True, null=True, verbose_name='cover video url'),
        ),
    ]
