# Generated by Django 6.0 on 2025-12-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_content_alter_lesson_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='video url'),
        ),
    ]
