# Generated by Django 6.0 on 2025-12-26 09:00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_video_file_alter_lesson_video_url'),
    ]

    operations = [
        # First, delete any quizzes that don't have a lesson (if any exist)
        migrations.RunSQL(
            "DELETE FROM courses_quiz WHERE lesson_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Remove course field
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        # Make lesson required (non-nullable)
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quizzes',
                to='courses.lesson'
            ),
        ),
    ]
