# Generated by Django 6.0 on 2026-01-02 21:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_course_alter_quiz_created_by_and_more'),
        ('users', '0004_alter_profile_date_of_birth_parent_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], db_index=True, default='pending_payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('free', 'Free'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, help_text='card, bank_transfer, wallet, etc.', max_length=50)),
                ('total_watch_time_minutes', models.IntegerField(default=0)),
                ('quiz_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('paid_by_parent', models.ForeignKey(blank=True, help_text='Parent who paid for this enrollment (if student is minor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_enrollments', to='users.parent')),
                ('user', models.ForeignKey(help_text='Student enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='courses_cou_user_id_e553f2_idx'), models.Index(fields=['course', 'status'], name='courses_cou_course__4e6f05_idx'), models.Index(fields=['paid_by_parent', 'payment_status'], name='courses_cou_paid_by_5231ad_idx'), models.Index(fields=['payment_status', 'status'], name='courses_cou_payment_aeb23b_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
