# Generated by Django 6.0 on 2026-01-02 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='courses_cou_paid_by_5231ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='courses_cou_payment_aeb23b_idx',
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='assignment_average_score',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='certificate_issued',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='certificate_issued_at',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='paid_by_parent',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='transaction_id',
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
    ]
